---
book: true
top-level-division: chapter
classoption: oneside

toc: true
toc-depth: 2
toc-own-page: true
number_sections: true
lof: true

header-right: "ANNE Analysis Challenge Event"

titlepage: true
titlepage-text-color: FFFFFF
titlepage-rule-color: FFFFFF
titlepage-background: config/front-page-background

page-background: config/all-page-background
page-background-opacity: 0.8

linkcolor: blue

bibliography: config/references.bib
natbib: true
natbiboptions: round
---
